name: Daily Commit

on:
  workflow_dispatch: 
  schedule:
    - cron: '43 13 * * *'  # Runs at 2:30 PM UTC every day

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f1001231@ds.study.iitm.ac.in
        run: |
          echo "Daily update $(date)" >> daily_update.txt
       

