name: Daily Commit

on:
  workflow_dispatch: 
  schedule:
    - cron: '43 13 * * *'  # Runs at 2:30 PM UTC every day

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create daily commit (23f1001231@ds.study.iitm.ac.in)
        run: |
          echo "Daily update $(date)" >> daily_update.txt
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add daily_update.txt
          git commit -m "Daily automated commit"
          git push

